import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import GlobalProviders from "@/context";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rotate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <GlobalProviders>{children}</GlobalProviders>
      </body>
    </html>
  );
}
